INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr. Chocolate", 6, "M", "brown", "Calm and Collected", )
INSERT INTO bears (name) VALUES ("Rowdy")
INSERT INTO bears (name) VALUES ("Tabitha")
INSERT INTO bears (name) VALUES ("Sergeant Brown")
INSERT INTO bears (name) VALUES ("Melissa")
INSERT INTO bears (name) VALUES ("Grinch")
INSERT INTO bears (name) VALUES ("Wendy")
INSERT INTO bears (name) VALUES (NULL)